### task 1- creating new features

In [9]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("cleaned_titanic.csv")

In [4]:
df.head()

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,sex_encoded,embarked_C,embarked_Q,embarked_S
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,Unknown,1,0,1,0
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,Unknown,0,0,0,1
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,Unknown,1,0,1,0
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,Unknown,1,0,0,1
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,Unknown,0,0,0,1

In [6]:
#feature for family size 

df['family_size']=df["parch"]+df["sibsp"]+1

In [10]:
#is_child feature creation
df['is_child']=np.where(df['age']<12 , 1, 0)

In [11]:
df[['age', 'sibsp', 'parch','family_size','is_child']].head()

    age  sibsp  parch  family_size  is_child
0  34.5      0      0            1         0
1  47.0      1      0            2         0
2  62.0      0      0            1         0
3  27.0      0      0            1         0
4  22.0      1      1            3         0

### task 2- handeling date and text features

In [12]:
df.dtypes

passengerid      int64
survived         int64
pclass           int64
name               str
sex                str
age            float64
sibsp            int64
parch            int64
ticket             str
fare           float64
cabin              str
sex_encoded      int64
embarked_C       int64
embarked_Q       int64
embarked_S       int64
family_size      int64
is_child         int64
dtype: object

In [13]:
df['title']=df['name'].str.extract(r' ([A-Za-z]+)\.')

In [15]:
df['title'].value_counts()

title
Mr        240
Miss       78
Mrs        72
Master     21
Col         2
Rev         2
Ms          1
Dr          1
Dona        1
Name: count, dtype: int64

In [16]:
df['title'] = df['title'].apply(lambda x: x if x in ['Mr','Miss','Mrs','Master'] else 'Other')

In [20]:
df['title'].value_counts()

title
Mr        240
Miss       78
Mrs        72
Master     21
Other       7
Name: count, dtype: int64

In [21]:
df.to_csv('featured_titanic.csv', index=False)